/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#785652",
        "on-primary-container": "#442200",
        "primary-container": "#c08552",
        "primary-fixed": "#ffdcc2",
        "on-surface": "#1e1b17",
        "surface-container-highest": "#e8e1da",
        "tertiary-container": "#b08884",
        "surface-container-low": "#f9f3eb",
        "secondary-fixed-dim": "#f9b894",
        "on-error": "#ffffff",
        "surface-container": "#f4ede5",
        "tertiary-fixed": "#ffdad6",
        "background": "#fff8f1",
        "outline": "#847469",
        "secondary-container": "#ffbe99",
        "on-tertiary-container": "#3e2320",
        "on-surface-variant": "#51443a",
        "on-tertiary-fixed-variant": "#5e3f3b",
        "surface-dim": "#dfd9d1",
        "on-tertiary-fixed": "#2d1512",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f7f0e8",
        "primary": "#855324",
        "inverse-primary": "#fbb981",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "inverse-surface": "#33302b",
        "on-secondary-container": "#7a4b2e",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#2e1500",
        "outline-variant": "#d6c3b6",
        "tertiary-fixed-dim": "#e8bcb7",
        "on-primary": "#ffffff",
        "surface-container-high": "#eee7df",
        "surface-tint": "#855324",
        "secondary-fixed": "#ffdbc9",
        "on-secondary-fixed-variant": "#683c20",
        "surface": "#fff8f1",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#693c0f",
        "on-secondary": "#ffffff",
        "secondary": "#835335",
        "on-secondary-fixed": "#321200",
        "surface-variant": "#e8e1da",
        "primary-fixed-dim": "#fbb981",
        "on-background": "#1e1b17",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
